name: Release CLI

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: npm
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.LIFEOMIC_NPM_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 16
        registry-url: https://registry.npmjs.org
    - name: Build and Test
      run: |
        echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
        yarn install
        yarn test
        yarn build
        yarn semantic-release
